title: theDocs Portal
description: theDocs Portal is my repository for documenting and referencing steps I took while working on projects I am interested in.
theme: just-the-docs

# url: https://just-the-docs.github.io

# External navigation links
# nav_external_links:
#   - title: Just the Docs on GitHub
#     url: https://github.com/just-the-docs/just-the-docs
#     hide_icon: true # set to true to hide the external link icon - defaults to false
#     opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

favicon_ico: "/assets/images/favicon.ico"
search_enabled: false

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue