# Project information
site_name: myDocs Portal
# defeine TOC or order of website-
nav:
  - Home: index.md
#  - 'my Projects':
#    - 'Proxmox Virtual Environment':
#      - 'projects/pageA.md'

#   - 'Docker':
#      - 'projects/pageB.md'


site_author: Jack McCullagh
site_description: >-
  The purpose of myDocs Portal is to be a placeholder where I will document outcomes of projects that I'm about to undertake.

# Repository
# repo_name: ---/REPO_NAME
# repo_url: https://github.com/---------/REPO_NAME

# Configuration
theme:
  font:
    text: Roboto
  name: material
  features:
#    - navigation.tabs
#    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/#
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/#
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/#
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/#

# extra_javascript:


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - footnotes
  
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      
plugins:
  - search

copyright: |
  &copy; 2024 -  <a href="https://jmccu2010.github.io/thedocs/"  target="_blank" rel="noopener">myDocs Portal - Jack McCullagh</a>
