# Project information
site_name: REPO_NAME_OR_SITE_NAME
# defeine TOC or order of website-
nav:
  - Home: index.md

site_author: ---------
site_description: >-
  DESCRIPTION

# Repository
repo_name: ---/REPO_NAME
repo_url: https://github.com/---------/REPO_NAME

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/---------
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/---------
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/---------
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/---------/

extra_javascript:


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/---------"  target="_blank" rel="noopener">---------</a>